### PR TITLE
Update class-savvii-dashboard.php

### PR DESCRIPTION
**Pull request by ericmulder**
As discussed in issue #4 a pull request to move the menu item between the other plugins.

### CODE REVIEW

**Comment by ericmulder** [comment]
Any updates on this?

**Comment by fuegas** [comment]
I see that you've altered only the code and not the related testsuite. As you can see the build is currently failing because of this and until that is fixed we can't merge this request. How we run our tests can be found in [DEVELOPMENT.md](https://github.com/Savvii/warpdrive/blob/master/DEVELOPMENT.md#testing).

As @ghovens stated in #4, we're currently building different features that are requested by many customers. I guess we can start working on this within a few weeks when we've started releasing those features.

**Comment by ericmulder** [comment]
Thanks, would you suggest I will wait for you, or shall I also fix the test?

**Comment by schellingerht** [comment]
Hi @ericmulder,

Thank you very much for your contribution!

Version [2.9.0](https://github.com/Savvii/warpdrive/releases/tag/2.9.0) provides 1) the relocation of the left Warpdrive menu item to the settings menu and 2) the functionality for the Warpdrive top menu.

**Pull request closed without merging**
